services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userscode
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - react-network

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - react-network

  backend:
    build:
      context: ./SharpCodeRunner.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - react-network
    depends_on:
      - postgres

networks:
  react-network:
    driver: bridge
